server:
  port: 8080

spring:
  application:
    name: consumer-A

# EurekaClientConfigBean定义了各种客户端配置属性
eureka:
  client:
    # 消费者不需要注册到注册中心
    register-with-eureka: false
    # 启用服务消费者从注册中心拉取服务列表的功能
    fetch-registry: true
    # 设置服务消费者从注册中心拉取服务列表的间隔
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka


