spring:
  application:
    name: producer-A
  datasource:
    #   数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asdfre#@!
    url: jdbc:mysql://10.10.10.199:3306/testss?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    #   Druid数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true

eureka:
  instance:
    # 使用IP注册到eureka，默认是使用操作系统的hostname
    prefer-ip-address: true
    # 指定实例名
    instance-id: ${spring.application.name}:${server.port}
  client:
    # 服务提供方注册到eureka
    registerWithEureka: true
    # 关闭服务提供方从注册中心拉取服务列表功能，服务提供方只注册服务，不需要获取服务列表
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml # mybatis配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper映射文件
  type-aliases-package: com.xchl.springcloud.model #实体类文件包路径

---
spring:
  profiles: p1
server:
  port: 8081

---
spring:
  profiles: p2
server:
  port: 8082






